"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var commands;
(function (commands) {
    commands["movieLightsEnd"] = "movieLightsEnd";
    commands["movieLights"] = "movieLights";
    commands["defaultBrightness"] = "defaultBrightness";
    commands["setDefaultColor"] = "setDefaultColor";
    commands["defaultColor"] = "defaultColor";
    commands["lightsOff"] = "lightsOff";
    commands["lightsOn"] = "lightsOn";
    commands["mediaRoomOn"] = "mediaRoomOn";
    commands["mediaRoomOnSlow"] = "mediaRoomOnSlow";
    commands["sewingLights"] = "sewingLights";
    commands["movieLightsUpstairs"] = "movieLightsUpstairs";
    commands["movieLightsEndUpstairs"] = "movieLightsEndUpstairs";
    commands["nightMode"] = "nightMode";
    commands["lightsOut"] = "lightsOut";
    commands["outsideOff"] = "outsideOff";
    commands["outsideOn"] = "outsideOn";
    commands["sunrise"] = "sunrise";
    commands["acOff"] = "acOff";
    commands["acOn"] = "acOn";
    commands["guestMode"] = "guestMode";
    commands["guestModeOff"] = "guestModeOff";
    commands["romantic"] = "romantic";
    commands["areYouThere"] = "areYouThere?";
    commands["RaspberryPi"] = "RaspberryPi";
    commands["neaMedicineReminder"] = "neaMedicineReminder";
    commands["medicineTaken"] = "medicineTaken";
    commands["morningSunrise"] = "morningSunrise";
    commands["sunset"] = "sunset";
    commands["eveningRelaxLights"] = "eveningRelaxLights";
    commands["austinBedsideButton"] = "austinBedsideButton";
    commands["neaBedsideButton"] = "neaBedsideButton";
    commands["nursing"] = "nursing";
    commands["naptime"] = "naptime";
    commands["bedroomOn"] = "bedroomOn";
    commands["bedroomOff"] = "bedroomOff";
    commands["bedroomDefault"] = "bedroomDefault";
    commands["bedroomPartyLights"] = "bedroomPartyLights";
    commands["bedroomPartyLightsEnd"] = "bedroomPartyLightsEnd";
    commands["videoCall"] = "videoCall";
    commands["halloween"] = "halloween";
    commands["halloweenOff"] = "halloweenOff";
    commands["livingRoomOn"] = "livingRoomOn";
    commands["livingRoomOff"] = "livingRoomOff";
    commands["plantOn"] = "plantOn";
    commands["plantOff"] = "plantOff";
    commands["gitPull"] = "gitPull";
})(commands = exports.commands || (exports.commands = {}));
;
